name: Volumetria de Clientes

on:
  schedule:
    - cron: "0 11 * * 1"  # toda segunda às 08h Brasília
  workflow_dispatch:       # permite rodar manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          METABASE_URL:                ${{ secrets.METABASE_URL }}
          METABASE_API_KEY:            ${{ secrets.METABASE_API_KEY }}
          SLACK_WEBHOOK_URL:           ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python main.py
